---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: hello-world
  namespace: hello-world
spec:
  interval: 10m0s
  ref:
    branch: main
  url: https://github.com/yitsushi/hello-world

